### ISSUE TITLE
Encontrei um problema!

### ISSUE THREAD

**Issue by balasclava** [hudsonbrendon/picpay-python#14]
Olá! 😶‍🌫️
Primeiramente, obrigado por fazer esse código!

Achei um problema na função de cancelar os pagamentos; como diz na [documentação oficial do Picpay](https://studio.picpay.com/produtos/e-commerce/checkout/guides/cancel-order), caso o pagamento já esteja aprovado, é necessário o `authorizationId` além do `referenceId`, porém no seu código, só trabalha um parâmetro, independente da condição...

``` Python
def cancellation(self, reference_id: str) -> dict:
        # Documentação da função...

        path = f"payments/{reference_id}/cancellations"

        json = {  # Aqui deveria ter o parâmetro "authorizationId".
            "referenceId": reference_id,
        }

        request = self._request(method="post", path=path, json=json)

        return request
```

Mas no caso, creio que poderia ser um parâmetro opcional, já que não é necessário passar a autorização sempre ⏑

<details>
  <summary>Documentação do PicPay! 🪙</summary>

  ![image](https://user-images.githubusercontent.com/71716568/159496894-4b3dc9c5-37ce-4902-bc69-c0b308073491.png)
  
</details>

<details>
  <summary>Sugestão de solução? 🫂</summary>
  
  Essa foi a forma em que pensei.
  Novamente, muito obrigado pelo seu trabalho, me ajudou bastante!
  
  ``` Python
  def cancellation(self, reference_id: str, authorization_id: str = None) -> dict:
          path = f"payments/{reference_id}/cancellations"

          json = {
              "referenceId": reference_id,
          }

          if authorization_id:
              json["authorizationId"] = authorization_id

          request = self._request(method="post", path=path, json=json)

          return request
  ```
  
</details>

**Comment by hudsonbrendon** [comment]
Boa cara, manda um PR se possível, se não assim, que possível eu corrijo isso.
